// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slzznorqwdejbhlssyfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsenpub3Jxd2RlamJobHNzeWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDk5MTUsImV4cCI6MjA2MjM4NTkxNX0.j3e6lRp6zKP0JR2Lx6JBfWMFMLp3QNpKk5M4f_6pD2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);